controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\helpers\ArrayHelper;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\servicios;
use app\models\planes;
use app\models\componen;
use app\models\ContratoForm;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        
         $dataProvider = new ActiveDataProvider([
             'query' => servicios::find()
                 ->select("nombre,id")->distinct(),
         
         ]);

        
        return $this->render("index",[
            "resultados"=>$dataProvider,
            "campos"=>['nombre','id'],
        ]);

   
        
    }
      public function actionPlanescontrato($servicio)
    {



//                 
                $dataProvider = new ActiveDataProvider([    
                'query' => componen::find()
                   ->select("planes.id id_plan,planes.titulo titulo,
                                planes.velocidad velocidad,planes.llamadas llamadas,
                                planes.datos datos,planes.descripcion descripcion,tarifa")
                   ->innerJoinWith('servicios')
                   ->innerJoinWith('planes')  
//                    ->innerJoin('planes','componen.plan = planes.id')
//                    ->innerJoin('servicios','componen.servicio = servicios.id')
                    ->where('componen.servicio ='.$servicio),
                    
           ]);    
               
        
                
       //  ]);
//        $resultado = $dataProvider->getModels();
//        $array_resultado=[];
//        foreach($resultado as $resul){
//            $array_resultado['tipo'] = $resul['tipo']; 
//            $array_resultado['titulo'] = $resul['titulo']; 
//            $array_resultado['vel'] = $resul['vel']; 
//            $array_resultado['tel'] = $resul['tel']; 
//            $array_resultado['dat'] = $resul['dat']; 
//            $array_resultado['descplan'] = $resul['descplan']; 
//            $array_resultado['tar '] = $resul['tar']; 
//        }
       
//        echo("<pre>");
//         var_dump($dataProvider);
//         echo("</pre>");
//         exit;
        
        return $this->render("planes",[
            "resultados"=>$dataProvider,
            "campos"=>['id_plan','titulo','velocidad','llamadas','datos','descripcion','tarifa'],
//            "titulo"=>"Planes del Servicio",
//            "enunciado"=>"Información sobre el plan",
//            "sql"=>"SELECT p.tipo tipo, p.titulo titulo, p.velocidad vel, p.llamadas tel,p.datos dat,p.descripcion descplan,c.descripcion descomponen,c.tarifa tar 
//                                    FROM componen c INNER JOIN servicios s ON c.servicio = s.id 
//                                                    INNER JOIN planes p ON c.plan = p.id
//                                                    WHERE c.servicio = $servicio",

        ]);

   
        
    }


     public function actionInfoplan()
    {
         $miplan = $_POST['plan'];
         if(isset($_POST['plan'])){
             $informacionPlan = new SqlDataProvider([
                'sql' => "select componen.id,componen.tarifa,planes.tipo,planes.titulo,
                                             planes.velocidad,planes.llamadas,planes.datos,
                                             planes.descripcion
                         from componen join planes on componen.plan = planes.id where planes.id = '$miplan'",   
           ]); 
            
           
             //return json_encode($myArray);
//             $info_planes = json_decode($informacionPlan);
//             return $info_planes;
            $resultado = $informacionPlan->getModels();
            $array_plan = json_encode($resultado);
            return $array_plan;
           
           
//             $array_info = ['servicio'=>$resultado[0]['id'],
//                            'tarifa'=>$resultado[0]['tarifa'],
//                            'tipo'=>$resultado[0]['tipo'],
//                            'titulo'=>$resultado[0]['titulo'],
//                            'velocidad'=>$resultado[0]['velocidad'],
//                            'llamadas'=>$resultado[0]['llamadas'],
//                            'datos'=>$resultado[0]['datos'],
//                            'descripcion'=>$resultado[0]['descripcion'],
//                            ];
        
//                                
         }


    }
    
    
    public function actionFormular_contrato(){
      
        $model = new contratoForm();
     
         return $this->render('formularioContrato', [
            'model' => $model,
        ]);
        
       
    }
    
     public function actionValida(){
         //$modeloDatos = $_POST->getModels();
//         var_dump($_POST['ContratoForm']);
//         exit;
      
         $model = new ContratoForm();
            if (Yii::$app->request->isPost) {
              
                if ($model->upload()) {
                    // el archivo fue subido exitosamente
                    return;
                }
            }
         
         
        if ($model->load(Yii::$app->request->post()) && $model->envioFormContrato(Yii::$app->params['adminEmail'])) {
          
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('formularioContrato', [
            'model' => $model,
        ]);    
            
            
     }
     
//      public function actionFirma()
//    {
//      
//         return $this->render('firmaelectronica');
//    
//    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/_bloques.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use app\models\servicios;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ServiciosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
 
?>

    <div class="col-md-6 col-sm-12 text-md-right text-sm-center bloque">
        <button id="bloque_servicio_<?=$model->id?>" class="bloque_servicio" type="button" class="btn">
            <a href="./planescontrato/?servicio=<?=$model->id?>"> 
          
                <div class="img_bloque">
                    <img src="<?= Url::to('@web/imagenes/servicios/'.$model->id.'.'.'png')?>"/>
                    <div id="nombre_servicio">
                        <?= ucfirst(strtolower($model->nombre)) ?>
                        
                    </div>
                    <div id="id_servicio"dd
                        <a href="_bloquesPlanesel.php"></a>
                    </div>
                </div>
            </a>
        </button>
    </div>

    

views/site/_bloquesPlanes.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use app\models\servicios;
use app\models\componen;
use app\models\planes;



/* @var $this yii\web\View */
/* @var $searchModel app\models\ServiciosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>

    <div class="col-sm-12 col-md-6 btn-block">
<!--        <div class="btn-block">-->
            
            
            <button class="btn btn-block btn-info boton" onclick="mostrar_infoPlan(<?=$model->id_plan?>)"><?=$model->titulo?></button>
<!--       Html::button($model->titulo,['class'=>'btn-block btn-info boton'], [
            'onclick'=>"
             $.ajax({
            type     :'POST',
            cache    : false,
            url  : '/site/infoplan',
            success  : function(response) {
            console.log(response);
                $('#informaPlan').html(response);
            }
            });return false;",
                        ]);-->
            
            
            
            
            
            
<!--        	Html::button($model->titulo,['class'=>'btn-block btn-info boton'],   
            ['onclick' => '
              $.ajax({
                      type: "POST",
                      url: "/site/infoplan",
                      data: {plan: '.$model->id_plan.'}, 
                      success: function(resultado) {

                                 
                                      console.log(resultado);
                                
                                },
                       error: function(data) {
                               console.log(\"server error\");
                        }
            });
        ']
                      
      );-->

          
     


<!--        </div>-->
       
    </div>


<script type="text/javascript">
function mostrar_infoPlan(plan){
    
    
        $.ajax({
        type: "POST",
        url: "../infoplan/",
        data: {plan:plan}, 
        dataType: "json",
        success: function(resultado) {
                       var plan = resultado[0]['id_plan'];
                      var bloque_info = "<h3>"+resultado[0]['titulo']+"</h3>";
                       bloque_info += "<ul><li>"+resultado[0]['descripcion']+"</li>";
                       bloque_info += "<li>Cuota "+resultado[0]['tarifa']+" €/mes IVA incluido"+"</li>";                   
                       bloque_info += "<li>Sin límite de descarga</li>";
                       bloque_info += "<li>Sin permanencia</li>";
                       bloque_info += "<li>Sin necesidad de línea telefónica</li></ul>";
                       bloque_info += "<button class='btn btn-block btn-info' onclick=\"formulario_contrato('" + plan + "');\">Contratar</button>";
                       //bloque_info += "<?= Html::a('Contratar', array('site/formulaContrato')); ?>"
                      $('#informaPlan').html(bloque_info);  
                 
                      
                     
                 
                  },
         error: function(data) {
                 console.log("server error");
          }
            }); 
   
}

function formulario_contrato(plan){
//window.location.href = '../formular_contrato?producto='+plan;
window.location.href = '../formular_contrato';
}

</script>

views/site/_formDocumentos.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="css/formulario_archivos.css">
	<!-- <link href="http://allfont.es/allfont.css?fonts=montserrat" rel="stylesheet" type="text/css" /> -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>Documentos | Contratar</title>
</head>
<body>
	<main>

		<div class="container">
			<div class="row">
				<div class="col-12 cabecera">
					<img src="images/logo.png"/>
				</div>
			</div>
			
			<h4>Adjuntar Documentos</h4>
			<div class="row">
				<div class="col-12 form-group">
					<h6>NIF o NIE</h6>
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Seleccionar archivo" />
						<span class=""input-group-btn>
							<div class="btn btn-info">...</div>
						</span>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-12 form-group">
					<h6>Número de Cuenta</h6>
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Seleccionar archivo" />
						<span class=""input-group-btn>
							<div class="btn btn-info">...</div>
						</span>
					</div>
				</div>
			</div>

			<h4>Portabilidades</h4>
			<div class="row">
				<div class="col-12 form-group">
					<h6>Portabilidad Teléfono Fijo</h6>
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Seleccionar archivo" />
						<span class=""input-group-btn>
							<div class="btn btn-info">...</div>
						</span>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-12 form-group">
					<h6>Portabilidad Teléfono Móvil</h6>
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Seleccionar archivo" />
						<span class="input-group-btn">
							<div class="btn btn-info">...</div>
						</span>
					</div>
				</div>
			</div>

			<h4>Empresas</h4>
			<div class="row">
				<div class="col-12 form-group">
					<h6>CIF o Recibo Autónomos</h6>
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Seleccionar archivo" />
						<span class=""input-group-btn>
							<div class="btn btn-info">...</div>
						</span>
					</div>
				</div>
			</div>

			<div class="row subir">
				<button type="button" class="btn btn-info btn-block">Subir Archivos</button>
			</div>


			<div class="row">

				<div class="col-md-6 col-sm-12 pie">
					<span class="textoazul">Información/Soporte</span><br/>
					<span><i class="fa fa-phone"></i> &nbsp; 942231563</span><br/>
					<span><i class="fa fa-phone"></i> &nbsp; 942049655</span><br/>
					<i class="fa fa-envelope"></i> &nbsp; <span class="textoazul">info@aoraconecta.com</span><br>
					<img src="images/logo_fondonegro.png"/><br/><br/>
				</div>
				<div class="col-md-6 col-sm-12 pie2">
					<a href="https://www.facebook.com/aoraconecta"><img src="images/facebook.png" alt="facebook"/></a>
					<a href="https://twitter.com/aoraconecta"><img src="images/twitter.png" alt="twitter"/></a>
					<a href="https://www.instagram.com/aoraconecta"><img src="images/instagram.png" alt="instagram"/></a>
				</div>

			</div>

		</div>
	</main>
</body>
</html>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
use yii\helpers\Url;
use yii\widgets\ListView;

?>

        <link rel="stylesheet" href="<?= Url::to('@web/css/servicios_bootstrap.css') ?>">
	<link href="http://allfont.es/allfont.css?fonts=montserrat" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>Servicios</title>
        
        
  <main>      


  <div class="cabecera">
    <img class="logo" src="<?= Url::to('@web/imagenes/logo.png') ?>"/>
  </div>

    <div class="body-content">

	
 
 <?= ListView::widget([
        'dataProvider' => $resultados,
         'itemView' => '_bloques',
         'layout'=>"{pager}{items}",
      
    ]);
        
    ?>
     
</div>
<!--    <div class="servicios-index">

      <div class="row">

        <div class="col-md-6 col-sm-12 pie">
                <span class="textoazul">Información/Soporte</span><br/>
                <span><i class="fa fa-phone"></i> &nbsp; 942231563</span><br/>
                <span><i class="fa fa-phone"></i> &nbsp; 942049655</span><br/>
                <i class="fa fa-envelope"></i> &nbsp; <span class="textoazul">info@aoraconecta.com</span><br>
                <img src="<?= Url::to('@web/imagenes/logo_fondonegro.png')?>"/><br/><br/>
        </div>
        <div class="col-md-6 col-sm-12 pie2">
                <a href="https://www.facebook.com/aoraconecta"><img src="<?= Url::to('@web/imagenes/facebook.png')?>" alt="facebook"/></a>
                <a href="https://twitter.com/aoraconecta"><img src="<?= Url::to('@web/imagenes/twitter.png')?>" alt="twitter"/></a>
                <a href="https://www.instagram.com/aoraconecta"><img src="<?= Url::to('@web/imagenes/instagram.png')?>" alt="instagram"/></a>
        </div>

    </div>
	


    </div>-->

</main>

<!--<script>
    window.addEventListener('load',(e)=>{
      
        let botones =  document.querySelectorAll('.bloque_servicio');
        for(let c=0;c < botones.length;c++){
          botones[c].addEventListener("click", (ev)=>{  
          let codigo= botones[c].querySelector("#id_servicio").innerText;
        
          });
      }
   
   
//    window.location.replace("Url::toRoute('site/planes')");
   }); 


    
</script>-->

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/planes.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
use yii\helpers\Url;
use yii\widgets\ListView;

?>
        <link rel="stylesheet" href="<?= Url::to('@web/css/planes.css')?>">
	<link href="http://allfont.es/allfont.css?fonts=montserrat" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<title>Planes</title>
        

  <div class="cabecera">
    <img class="logo" src="<?= Url::to('@web/imagenes/logo.png') ?>"/>
  </div>

<div class="body-content">
<div class="col-sm-12 col-md-6 wrap">
    

 <?= ListView::widget([
        'dataProvider' => $resultados,
         'itemView' => '_bloquesPlanes',
         'layout'=>"{pager}{items}",
      
    ]);
        
    ?>
 </div>    

      
<div id="informaPlan" class="col-sm-12 col-md-6">
    
</div>
</div>


<!--    <div class="servicios-index">-->
<!--<footer>
    
        <div class="container pieses">    
          <div class="col-md-6 col-sm-12 pie">
                  <span class="textoazul">Información/Soporte</span><br/>
                  <span><i class="fa fa-phone"></i> &nbsp; 942231563</span><br/>
                  <span><i class="fa fa-phone"></i> &nbsp; 942049655</span><br/>
                  <i class="fa fa-envelope"></i> &nbsp; <span class="textoazul">info@aoraconecta.com</span><br>
                  <img src="<?= Url::to('@web/imagenes/logo_fondonegro.png')?>"/><br/><br/>
          </div>
          <div class="col-md-6 col-sm-12 pie2">
                  <a href="https://www.facebook.com/aoraconecta"><img src="<?= Url::to('@web/imagenes/facebook.png')?>" alt="facebook"/></a>
                  <a href="https://twitter.com/aoraconecta"><img src="<?= Url::to('@web/imagenes/twitter.png')?>" alt="twitter"/></a>
                  <a href="https://www.instagram.com/aoraconecta"><img src="<?= Url::to('@web/imagenes/instagram.png')?>" alt="instagram"/></a>
          </div>
        </div>    

    
</footer>-->

views/site/recibiendoForm.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Clientes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="contrato-form">

    <h1>Formulario de contrato</h1> 
   
    <p><?=$_POST['nombre']?></p>
    <div class="form-group">
        <?= Html::submitButton('Enviar', ['class' => 'btn btn-success']) ?>
    </div>

  

</div>
    